name: windows_printer
description: "A Flutter plugin for managing and interacting with printers on Windows platforms."
version: 0.2.1
homepage: https://github.com/Manas-Basnet51/windows_printer
repository: https://github.com/Manas-Basnet51/windows_printer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0' 

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsPrinterPluginCApi